// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG25oaZc2e1feis6-64cAFgGVyZYzvtaQ',
    appId: '1:467430443422:web:f602e1f0c39d7a0fe1ee8f',
    messagingSenderId: '467430443422',
    projectId: 'mobiledev-amal',
    authDomain: 'mobiledev-amal.firebaseapp.com',
    storageBucket: 'mobiledev-amal.appspot.com',
    measurementId: 'G-BGTHBENJ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgSu9Uaxn5Q5QXcJQdRuGwnnDzZdNwyBo',
    appId: '1:467430443422:android:e7546cab1ad85d36e1ee8f',
    messagingSenderId: '467430443422',
    projectId: 'mobiledev-amal',
    storageBucket: 'mobiledev-amal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfrMWgpvkOH_4VwBKx0AljI_UP7GGIRJ4',
    appId: '1:467430443422:ios:0ec8b5958c688b40e1ee8f',
    messagingSenderId: '467430443422',
    projectId: 'mobiledev-amal',
    storageBucket: 'mobiledev-amal.appspot.com',
    iosBundleId: 'com.example.mobiledev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfrMWgpvkOH_4VwBKx0AljI_UP7GGIRJ4',
    appId: '1:467430443422:ios:0ec8b5958c688b40e1ee8f',
    messagingSenderId: '467430443422',
    projectId: 'mobiledev-amal',
    storageBucket: 'mobiledev-amal.appspot.com',
    iosBundleId: 'com.example.mobiledev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG25oaZc2e1feis6-64cAFgGVyZYzvtaQ',
    appId: '1:467430443422:web:f25e0d740f4aa304e1ee8f',
    messagingSenderId: '467430443422',
    projectId: 'mobiledev-amal',
    authDomain: 'mobiledev-amal.firebaseapp.com',
    storageBucket: 'mobiledev-amal.appspot.com',
    measurementId: 'G-7T9TF08V62',
  );
}
